-- Migration: 001_visitors
-- Purpose: Create visitors table to track anonymous visitors arriving from Google Ads.
--          Stores gclid, UTM parameters, IP hash (privacy-safe), user agent, and session
--          timing for lead attribution and offline conversion matching.
--
-- Service role bypasses RLS. API routes use service role for all writes.

-- ---------------------------------------------------------------------------
-- Table: visitors
-- ---------------------------------------------------------------------------

CREATE TABLE visitors (
  id              UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Visitor identity (cookie-stored ID generated by middleware in Phase 8)
  visitor_id      TEXT        NOT NULL UNIQUE,

  -- Google Ads click ID (only click ID for v1.1 — no fbclid/msclkid per CONTEXT decision)
  gclid           TEXT,

  -- UTM attribution parameters
  utm_source      TEXT,
  utm_medium      TEXT,
  utm_campaign    TEXT,
  utm_term        TEXT,
  utm_content     TEXT,

  -- Privacy-safe identifiers (raw values never stored)
  ip_hash         TEXT,        -- SHA-256 hash of client IP address
  user_agent      TEXT,

  -- Session context
  landing_page    TEXT,        -- First page visited (full URL)
  referrer        TEXT,        -- HTTP Referer header value

  -- Timestamps
  first_seen_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- visitor_id is already covered by the UNIQUE constraint; listed explicitly
-- here so the intent is documented in code.
CREATE INDEX idx_visitors_visitor_id
  ON visitors (visitor_id);

-- Partial index: only index rows where gclid is present.
-- Used for lead-to-click matching at offline conversion upload time.
CREATE INDEX idx_visitors_gclid
  ON visitors (gclid)
  WHERE gclid IS NOT NULL;

-- For cleanup and analytics queries that scan by recency.
CREATE INDEX idx_visitors_last_seen_at
  ON visitors (last_seen_at);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

ALTER TABLE visitors ENABLE ROW LEVEL SECURITY;

-- No permissive policies are created.
-- With RLS enabled and no policies, the Supabase default is DENY ALL for the
-- anon role. Service role bypasses RLS and is used exclusively by API routes.
